/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TranscribeRouteImport } from './routes/transcribe'
import { Route as ApiTranscriptionsIndexRouteImport } from './routes/api/transcriptions/index'
import { Route as ApiTranscriptionsIdRouteImport } from './routes/api/transcriptions/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscribeRoute = TranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionsIndexRoute = ApiTranscriptionsIndexRouteImport.update({
  id: '/api/transcriptions/',
  path: '/api/transcriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionsIdRoute = ApiTranscriptionsIdRouteImport.update({
  id: '/api/transcriptions/$id',
  path: '/api/transcriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/transcribe': typeof TranscribeRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions/': typeof ApiTranscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/transcribe': typeof TranscribeRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions': typeof ApiTranscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/transcribe': typeof TranscribeRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions/': typeof ApiTranscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/transcribe'
    | '/api/transcriptions/$id'
    | '/api/transcriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/transcribe'
    | '/api/transcriptions/$id'
    | '/api/transcriptions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/transcribe'
    | '/api/transcriptions/$id'
    | '/api/transcriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  TranscribeRoute: typeof TranscribeRoute
  ApiTranscriptionsIdRoute: typeof ApiTranscriptionsIdRoute
  ApiTranscriptionsIndexRoute: typeof ApiTranscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcribe': {
      id: '/transcribe'
      path: '/transcribe'
      fullPath: '/transcribe'
      preLoaderRoute: typeof TranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/': {
      id: '/api/transcriptions/'
      path: '/api/transcriptions'
      fullPath: '/api/transcriptions/'
      preLoaderRoute: typeof ApiTranscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/$id': {
      id: '/api/transcriptions/$id'
      path: '/api/transcriptions/$id'
      fullPath: '/api/transcriptions/$id'
      preLoaderRoute: typeof ApiTranscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  TranscribeRoute: TranscribeRoute,
  ApiTranscriptionsIdRoute: ApiTranscriptionsIdRoute,
  ApiTranscriptionsIndexRoute: ApiTranscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
