/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TranscribeRouteImport } from './routes/transcribe'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicTranscriptionWebhookRouteImport } from './routes/api/public/transcription-webhook'
import { Route as ApiTranscriptionsIndexRouteImport } from './routes/api/transcriptions/index'
import { Route as ApiTranscriptionsIdRouteImport } from './routes/api/transcriptions/$id'
import { Route as ApiTranscriptionsJobsIndexRouteImport } from './routes/api/transcriptions/jobs/index'
import { Route as ApiTranscriptionsJobsJobIdRouteImport } from './routes/api/transcriptions/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscribeRoute = TranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscriptionWebhookRoute =
  ApiPublicTranscriptionWebhookRouteImport.update({
    id: '/api/public/transcription-webhook',
    path: '/api/public/transcription-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTranscriptionsIndexRoute = ApiTranscriptionsIndexRouteImport.update({
  id: '/api/transcriptions/',
  path: '/api/transcriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionsIdRoute = ApiTranscriptionsIdRouteImport.update({
  id: '/api/transcriptions/$id',
  path: '/api/transcriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionsJobsIndexRoute =
  ApiTranscriptionsJobsIndexRouteImport.update({
    id: '/api/transcriptions/jobs/',
    path: '/api/transcriptions/jobs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTranscriptionsJobsJobIdRoute =
  ApiTranscriptionsJobsJobIdRouteImport.update({
    id: '/api/transcriptions/jobs/$jobId',
    path: '/api/transcriptions/jobs/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transcribe': typeof TranscribeRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/transcription-webhook': typeof ApiPublicTranscriptionWebhookRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions/': typeof ApiTranscriptionsIndexRoute
  '/api/transcriptions/jobs/$jobId': typeof ApiTranscriptionsJobsJobIdRoute
  '/api/transcriptions/jobs/': typeof ApiTranscriptionsJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transcribe': typeof TranscribeRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/transcription-webhook': typeof ApiPublicTranscriptionWebhookRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions': typeof ApiTranscriptionsIndexRoute
  '/api/transcriptions/jobs/$jobId': typeof ApiTranscriptionsJobsJobIdRoute
  '/api/transcriptions/jobs': typeof ApiTranscriptionsJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transcribe': typeof TranscribeRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/transcription-webhook': typeof ApiPublicTranscriptionWebhookRoute
  '/api/transcriptions/$id': typeof ApiTranscriptionsIdRoute
  '/api/transcriptions/': typeof ApiTranscriptionsIndexRoute
  '/api/transcriptions/jobs/$jobId': typeof ApiTranscriptionsJobsJobIdRoute
  '/api/transcriptions/jobs/': typeof ApiTranscriptionsJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/transcribe'
    | '/api/public/openapi.json'
    | '/api/public/transcription-webhook'
    | '/api/transcriptions/$id'
    | '/api/transcriptions/'
    | '/api/transcriptions/jobs/$jobId'
    | '/api/transcriptions/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/transcribe'
    | '/api/public/openapi.json'
    | '/api/public/transcription-webhook'
    | '/api/transcriptions/$id'
    | '/api/transcriptions'
    | '/api/transcriptions/jobs/$jobId'
    | '/api/transcriptions/jobs'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/transcribe'
    | '/api/public/openapi.json'
    | '/api/public/transcription-webhook'
    | '/api/transcriptions/$id'
    | '/api/transcriptions/'
    | '/api/transcriptions/jobs/$jobId'
    | '/api/transcriptions/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TranscribeRoute: typeof TranscribeRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicTranscriptionWebhookRoute: typeof ApiPublicTranscriptionWebhookRoute
  ApiTranscriptionsIdRoute: typeof ApiTranscriptionsIdRoute
  ApiTranscriptionsIndexRoute: typeof ApiTranscriptionsIndexRoute
  ApiTranscriptionsJobsJobIdRoute: typeof ApiTranscriptionsJobsJobIdRoute
  ApiTranscriptionsJobsIndexRoute: typeof ApiTranscriptionsJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcribe': {
      id: '/transcribe'
      path: '/transcribe'
      fullPath: '/transcribe'
      preLoaderRoute: typeof TranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcription-webhook': {
      id: '/api/public/transcription-webhook'
      path: '/api/public/transcription-webhook'
      fullPath: '/api/public/transcription-webhook'
      preLoaderRoute: typeof ApiPublicTranscriptionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/': {
      id: '/api/transcriptions/'
      path: '/api/transcriptions'
      fullPath: '/api/transcriptions/'
      preLoaderRoute: typeof ApiTranscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/$id': {
      id: '/api/transcriptions/$id'
      path: '/api/transcriptions/$id'
      fullPath: '/api/transcriptions/$id'
      preLoaderRoute: typeof ApiTranscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/jobs/': {
      id: '/api/transcriptions/jobs/'
      path: '/api/transcriptions/jobs'
      fullPath: '/api/transcriptions/jobs/'
      preLoaderRoute: typeof ApiTranscriptionsJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcriptions/jobs/$jobId': {
      id: '/api/transcriptions/jobs/$jobId'
      path: '/api/transcriptions/jobs/$jobId'
      fullPath: '/api/transcriptions/jobs/$jobId'
      preLoaderRoute: typeof ApiTranscriptionsJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TranscribeRoute: TranscribeRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicTranscriptionWebhookRoute: ApiPublicTranscriptionWebhookRoute,
  ApiTranscriptionsIdRoute: ApiTranscriptionsIdRoute,
  ApiTranscriptionsIndexRoute: ApiTranscriptionsIndexRoute,
  ApiTranscriptionsJobsJobIdRoute: ApiTranscriptionsJobsJobIdRoute,
  ApiTranscriptionsJobsIndexRoute: ApiTranscriptionsJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
